version: "3.8"
services:
  wafcraft:
    build: .
    working_dir: /app
    volumes:
      - ./wafcraft:/app/wafcraft
    ports:
      - "8888:8888" # HostPort:ContainerPort
    deploy:
      resources:
        limits:
          cpus: "8.0" # Limit to 8 cores
          memory: 12000M # Limit to 12 GB RAM
        reservations:
          cpus: "0.5" # Reserve 0.5 cores
          memory: 200M # Reserve 200 MB RAM
